<?php

/**
 * @file
 * Handles drupal.org project data.
 */

/**
 * Drupal.org full project GIT URL.
 */
define('SIMPLYTEST_PROJECTS_DRUPAL_ORG_PROJECT', 'git://git.drupal.org/project/');

/**
 * Drupal.org sandbox project GIT URL.
 */
define('SIMPLYTEST_PROJECTS_DRUPAL_ORG_SANDBOX', 'git://git.drupal.org/sandbox/');

/**
 * Drupal.org webgit URL.
 */
define('SIMPLYTEST_PROJECTS_DRUPALCODE_ORG', 'http://drupalcode.org/');

/**
 * Drupal.org URL
 */
define('SIMPLYTEST_PROJECTS_DRUPAL_ORG', 'http://drupal.org/');

/**
 * Implements hook_menu().
 */
function simplytest_projects_menu() {
  $items = array();
  // General configuration form.
  $items['admin/simplytest/project'] = array(
    'title' => 'Projects settings',
    'description' => 'Settings of the project listings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simplytest_projects_settings_form'),
    'access arguments' => array('administer simplytest'),
    'file' => 'simplytest_projects.admin.inc',
  );
  // Project list management.
  $items['admin/simplytest/projects'] = array(
    'title' => 'Projects',
    'description' => 'Manage project list.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simplytest_projects_management_form'),
    'access arguments' => array('administer simplytest'),
    'file' => 'simplytest_projects.admin.inc',
  );
  // Version cache listing of a project.
  $items['admin/simplytest/projects/%/versions'] = array(
    'title' => 'Project versions',
    'description' => 'Cached project version listing.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simplytest_projects_version_list_form', 3),
    'access arguments' => array('administer simplytest'),
    'file' => 'simplytest_projects.admin.inc',
  );
  // Edit a project entry.
  $items['admin/simplytest/projects/%/edit'] = array(
    'title' => 'Edit project information',
    'description' => 'Edit project information.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simplytest_projects_edit_form', 3),
    'access arguments' => array('administer simplytest'),
    'file' => 'simplytest_projects.admin.inc',
  );
  // Operation on a project entry.
  $items['admin/simplytest/projects/%/%'] = array(
    'title' => 'Edit project information',
    'description' => 'Edit project information.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simplytest_projects_operation', 3, 4),
    'access arguments' => array('administer simplytest'),
    'file' => 'simplytest_projects.admin.inc',
  );
  return $items;
}

/**
 * Returns available information about a project.
 *
 * @param string $project
 *  The projects shortname to return information about.
 *
 * @return array
 *  An assocciative array containing:
 *   - title: The human readable project title.
 *   - type: The projects type.
 *   - creator: The drupal.org user who created it.
 *   - giturl: The project's git url.
 *   - sandbox: Whether it's a sandbox.
 */
function simplytest_projects_get_project($project) {
  // Get general information from database.
  $data = db_select('simplytest_projects', 'p')
    ->fields('p', array('title', 'type', 'sandbox', 'creator'))
    ->condition('shortname', $project)
    ->execute()->fetchObject();

  if (!$data) {
    // Need to fetch initial project data.
    $data = simplytest_projects_fetch_project($project);
    if ($data === FALSE) {
      return FALSE;
    }
    $data = (object) $data;
  }

  // Generate the git url to clone the project from.
  if ($data->sandbox) {
    $giturl = SIMPLYTEST_PROJECTS_DRUPAL_ORG_SANDBOX . $data->creator . '/' . $project . '.git';
  }
  else {
    $giturl = SIMPLYTEST_PROJECTS_DRUPAL_ORG_PROJECT . $project . '.git';
  }

  return array(
    'title' => $data->title,
    'type' => $data->type,
    'creator' => $data->creator,
    'giturl' => $giturl,
    'sandbox' => (bool) $data->sandbox,
  );
}

/**
 * Searches the database for projects by prefix.
 *
 * @param string $string
 *  The prefix string to search projects for.
 * @param int $range
 *  Maximum number of results to return.
 *
 * @return array
 *  An array of standard objects containing:
 *   - title: The human readable project title.
 *   - type: The projects type.
 *   - shortname: The project machine/shortname.
 *   - sandbox: Whether it's a sandbox.
 */
function simplytest_projects_search_project($string, $range = 100) {
  $db_or = db_or()
    ->condition('title', db_like($string) . '%', 'LIKE')
    ->condition('shortname', db_like($string) . '%', 'LIKE');
  $result = db_select('simplytest_projects', 'p')
    ->fields('p', array('title', 'shortname', 'type', 'sandbox'))
    ->orderBy('sandbox', 'ASC')
    ->condition($db_or)
    ->range(0, $range)->execute()->fetchAll();

  if (is_array($result) && $result) {
    foreach ($result as $id => $entry) {
      // Check results for blacklisted projects.
      foreach (variable_get('simplytest_projects_blacklisted_projects', array()) as $blacklisted) {
        if ($entry->shortname == $blacklisted) {
          unset($result[$id]);
        }
      }
    }
  }
  else {
    $result = array();
  }
  return $result;
}

/**
 * Returns all available versions for a project.
 *
 * @param string $project
 *  The project's shortname to return available versions for.
 *
 * @return array
 *  An associative array containing:
 *   - tags: Existing tags of the project.
 *   - heads: Existing heads of the project. 
 */
function simplytest_projects_get_versions($project) {
  // Check blacklist for project.
  foreach (variable_get('simplytest_projects_blacklisted_projects', array()) as $blacklisted) {
    if ($project == $blacklisted) {
      return FALSE;
    }
  }
  // Try to get current version data out of database.
  $timeout = strtotime(variable_get('simplytest_projects_version_timeout', '-1 hour'));
  $result = db_select('simplytest_projects', 'p')
    ->fields('p', array('versions'))
    ->condition('shortname', $project)
    ->condition('timestamp', $timeout, '>')
    ->execute()->fetchField();
  // Found recent results in database.
  if ($result) {
    return unserialize($result);
  }
  else {
    // Need to fetch fresh results.
    return simplytest_projects_fetch_versions($project);
  }
}

/**
 * Fetches, saves and returns all available versions for a project.
 *
 * @param string $project
 *  The project's shortname to fetch available versions for.
 *
 * @return array
 *  An associative array containing:
 *   - tags: Existing tags of the project.
 *   - heads: Existing heads of the project.
 */
function simplytest_projects_fetch_versions($project) {
  // Check whether project is known in database.
  $project_data = simplytest_projects_get_project($project);

  if ($project_data['sandbox']) {
    $drupalcode_url = SIMPLYTEST_PROJECTS_DRUPALCODE_ORG . 'sandbox/' . $project_data['creator'] . '/' . $project . '.git';
  }
  else {
    $drupalcode_url = SIMPLYTEST_PROJECTS_DRUPALCODE_ORG . 'project/' . $project . '.git';
  }

  // Fetch tags by request.
  $result = drupal_http_request($drupalcode_url . '/tags');
  if (!isset($result->data) || $result->code != 200) {
    watchdog('simplytest_projects', 'Failed to fetch version data for %project (Requested tags).', array(
      '%project' => $project,
    ), WATCHDOG_WARNING);
    return FALSE;
  }
  // Try to match out a list of tags of the raw HTML.
  preg_match_all('!<a class="list name" href=".*">([^<]*)</a></td>!', $result->data, $tags);
  if(!isset($tags[1])) {
    watchdog('simplytest_projects', 'Failed to fetch version data for %project (Fetched tags).', array(
      '%project' => $project,
    ), WATCHDOG_WARNING);
    return FALSE;
  }

  // Fetch branches by request.
  $result = drupal_http_request($drupalcode_url . '/heads');
  if (!isset($result->data) || $result->code != 200) {
    watchdog('simplytest_projects', 'Failed to fetch version data for %project (Requested heads).', array(
      '%project' => $project,
    ), WATCHDOG_WARNING);
    return FALSE;
  }
  // Try to match out a list of tags of the raw HTML.
  preg_match_all('!<a class="list name" href=".*">([^<]*)</a></td>!', $result->data, $heads);
  if(!isset($heads[1])) {
    watchdog('simplytest_projects', 'Failed to fetch version data for %project (Fetch heads).', array(
      '%project' => $project,
    ), WATCHDOG_WARNING);
    return FALSE;
  }

  // Blacklist filters.
  $blacklisted_versions = variable_get('simplytest_projects_blacklisted_versions', array());
  foreach ($blacklisted_versions as $blacklisted) {
    foreach ($tags[1] as $key => $tag) {
      if (preg_match('!' . $blacklisted . '!', $tag)) {
        unset($tags[1][$key]);
      }
    }
    foreach ($heads[1] as $key => $head) {
      if (preg_match('!' . $blacklisted . '!', $head)) {
        unset($heads[1][$key]);
      }
    }
  }

  $versions = array(
    'tags' => drupal_map_assoc($tags[1]),
    'heads' => drupal_map_assoc($heads[1]),
  );

  // Save fresh data to database.
  $found = db_update('simplytest_projects')
    ->fields(array(
      'timestamp' => REQUEST_TIME,
      'versions' => serialize($versions),
    ))
    ->condition('shortname', $project)
    ->execute();

  watchdog('simplytest_projects', 'Fetched version data for %project.', array(
    '%project' => $project,
  ), WATCHDOG_NOTICE);

  return $versions;
}

/**
 * Fetches, saves and returns general project information.
 *
 * @param string $project
 *  The project's shortname to fetch information for.
 *
 * @return object
 *  A standard object containing:
 *   - title: Human readable project title
 *   - sandbox: Boolean whether it's a sandbox project.
 *   - type: What the projects type is.
 *   - creator: The projects creator.
 */
function simplytest_projects_fetch_project($project) {
  // Try as full project.
  $result = drupal_http_request(SIMPLYTEST_PROJECTS_DRUPAL_ORG . 'project/' . $project);
  $sandbox = FALSE;
  if ($result->code == 404 && is_numeric($project)) {
    // Fallback to sandbox project
    $result = drupal_http_request(SIMPLYTEST_PROJECTS_DRUPAL_ORG . 'node/' . $project);
    $sandbox = TRUE;
  }
  if ($result->code != 200 || !isset($result->data)) {
    watchdog('simplytest_projects', 'Failed to fetch initial data for %project (Request).', array(
      '%project' => $project,
    ), WATCHDOG_WARNING);
    return FALSE;
  }

  // Try to match out the project title.
  preg_match_all('!<div class="block-inner">[^<]*<h2>Issues for ([^<]*)</h2>!', $result->data, $title);
  if(!isset($title[1][0])) {
    watchdog('simplytest_projects', 'Failed to fetch initial data for %project (Fetch title).', array(
      '%project' => $project,
    ), WATCHDOG_WARNING);
    return FALSE;
  }
  $title = $title[1][0];

  // Try to match out the project type.
  preg_match_all('! active[^<]*"><a href="/project/[^<]*" class="[^<]*active">([^<]*)</a></li>!', $result->data, $type);
  if(isset($type[1][0])) {
    $type = $type[1][0];
  }
  else {
    watchdog('simplytest_projects', 'Failed to fetch initial data for %project (Fetch type).', array(
      '%project' => $project,
    ), WATCHDOG_WARNING);
    $type = NULL;
  }

  // Try to match out the creator name.
  if ($sandbox) {
    preg_match_all('!<li class="active" ><a href="/sandbox/([^<]*)/' . $project . '" class="active">View</a></li>!', $result->data, $creator);
    if(!isset($creator[1][0])) {
      watchdog('simplytest_projects', 'Failed to fetch initial data for %project (Fetch creator).', array(
        '%project' => $project,
      ), WATCHDOG_WARNING);
      return FALSE;
    }
    $creator = $creator[1][0];
  }
  else {
    preg_match_all('!<div class="submitted">Posted by <a href="[^<]*" title="View user profile.">([^<]*)</a> on <em>!', $result->data, $creator);
    if(!isset($creator[1][0])) {
      watchdog('simplytest_projects', 'Failed to fetch initial data for %project (Fetch creator).', array(
        '%project' => $project,
      ), WATCHDOG_WARNING);
      return FALSE;
    }
    $creator = $creator[1][0];
  }

  // Find out the type.
  $type = simplytest_projects_get_project_type($term);
  if ($type === FALSE) {
    // Unknown type, error.
    watchdog('simplytest_projects', 'Failed to fetch initial data for %project (Determine type).', array(
      '%project' => $project,
    ), WATCHDOG_WARNING);
    return FALSE;
  }

  // Build, log and save the new project data.
  $data = array(
    'title' => $title,
    'shortname' => $project,
    'sandbox' => (int) $sandbox,
    'type' => $type,
    'creator' => $creator,
  );

  watchdog('simplytest_projects', 'Fetch initial data for %project.', array(
    '%project' => $project,
  ), WATCHDOG_NOTICE);

  db_insert('simplytest_projects')
    ->fields($data)
    ->execute();

  return $data;
}

/**
 * Inserts initial project data into database by a SimpleXML object.
 */
function simplytest_projects_xml_insert_project($xml) {
  // Try to figure out project type by term.
  if (!isset($xml->terms->term[0]->value)) {
    return FALSE;
  }
  $type_term = (string) $xml->terms->term[0]->value;
  $type = simplytest_projects_get_project_type($term);

  if ($type === FALSE) {
    return FALSE;
  }

  $data = array(
    'title' => (string) $xml->title,
    'shortname' => (string) $xml->short_name,
    // Sandbox project?
    'sandbox' => (int) (is_numeric((string) $xml->short_name) && substr($xml->link, 0, 26) === SIMPLYTEST_PROJECTS_DRUPAL_ORG . 'sandbox/'),
    // Get project type, as it is referenced as tag.
    'type' => $type,
    // Git creator name (for sandbox projects).
    'creator' => (string) substr(substr($xml->link, 26), 0, -(strlen($xml->short_name) + 1)),
  );

  db_insert('simplytest_projects')
    ->fields($data)
    ->execute();
}

/**
 * Finds out the readable project type by term.
 */
function simplytest_projects_get_project_type($term) {
  switch ($type_term) {
    case 'Drupal core':
      return 'Drupal core';

    case 'Modules':
      return 'Module';

    case 'Themes':
      return 'Theme';

    case 'Distributions':
      return 'Distribution';

    default:
      return FALSE;
  }
}