<?php

/**
 * @file
 * Simplytest.me submission management.
 */

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Entity\EntityInterface;

const SIMPLYTEST_SUBMISSION_SERVICE_URL = 'https://spawn.sh';

/**
* Implements hook_form_FORM_ID_alter().
*/
function simplytest_submission_form_node_submission_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Disable some stuff for now.
  for ($delta = 0; $delta <= $form['field_drupal_projects']['widget']['#max_delta']; $delta++) {
    $widget = &$form['field_drupal_projects']['widget'][(string) $delta];
    //kint($widget);
    $widget['field_project_identifier']['widget']['#disabled'] = TRUE; // @todo needs autocomplete
    $widget['field_project_source']['widget']['#disabled'] = TRUE; // @todo support more sources than d.o
    $widget['field_project_version']['widget']['#disabled'] = TRUE; // @todo fetch versions...
  }
  //kint($form['field_drupal_projects']['widget']);
  $form['field_instance_runtime']['#disabled'] = TRUE; // @todo longer runtime disabled until more stable
  $form['field_webspace_secondary_dbs']['#disabled'] = TRUE; // @todo implement secondary db scripts
  $form['field_instance_snapshot_cache']['#disabled'] = TRUE; // @todo implement on spawn.sh

  // Redirect to progress page.
  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'simplytest_submission_submit_goto_progress';
    }
  }
}

/**
 * Form submit callback.
 *
 * Redirects to submission progress page after submission node creation.
 */
function simplytest_submission_submit_goto_progress($form, FormStateInterface $form_state) {
  // Remove node creation status message.
  drupal_get_messages('status');
  // Redirect.
  $form_state->setRedirect('entity.node.simplytest_submission_progress', [
    'node' => $form_state->getFormObject()->getEntity()->id(),
  ]);
}

/**
* Implements hook_ENTITY_TYPE_presave().
*
* @todo use own entity type instead of nodes (?)
* @todo http request for spawning container can take some time, would be better
*       to do that on the progress page.
*/
function simplytest_submission_node_presave(EntityInterface $entity) {
  //kint($entity->field_drupal_projects->value);
  //throw new Error();

  if ($entity->getType() !== 'submission') { // @todo simplytest_ prefix
    return;
  }

  // Request preparation.
  $url = SIMPLYTEST_SUBMISSION_SERVICE_URL;
  $url .= '/?' . http_build_query(array(
    // use $ drush sset simplytest_submission.service_token TOKEN
    // @todo provide config interface for this / or do it within rules UI
    'token' => \Drupal::state()->get('simplytest_submission.service_token'),
    'ttl' => $entity->field_instance_runtime->value,
    'image' => $entity->field_instance_image->value,
  ));

  // Build script.
  $script = simplytest_submission_build_script($entity);

  // Send request.
  $client = \Drupal::httpClient();
  $response = $client->request('POST', $url, [
    'headers' => array(
      'Accept' => 'application/json',
      'Content-Type' => 'application/octet-stream; charset=utf-8',
    ),
    'body' => $script,
  ]);

  // Check response.
  if ($response->getStatusCode() !== 201) {
    throw new Error('Invalid status code returned from spawn.sh api');
  }
  $data = json_decode($response->getBody(), true);
  if (!isset($data['id'])) {
    throw new Error('No id in spawn.sh response data');
  }

  // Save container ID as title.
  $entity->title->value = $data['id'];
  $entity->field_container_url->value = $data['url'];
  $entity->field_container_token->value = $data['token'];
}

/**
 * Generates the script to build the submission with.
 *
 * @todo move script building into rules (?)
 */
function simplytest_submission_build_script(EntityInterface $entity) {
  $script = [];
  $script[] = '#!/bin/bash';
  $script[] = 'export DEBIAN_FRONTEND=noninteractive';
  $script[] = 'set -x';
  $script[] = 'apt-get update';
  $script[] = 'apt-get upgrade -y';

  $packages = [];
  $packages[] = 'zip';
  $packages_script = [];

  // PHP.
  switch ($entity->field_webspace_interpreter->value) {
    case 'php7-fpm':
      $packages[] = 'php7.0-fpm';
      break;
    case 'mod-php7':
      // Installed in the apache2 part.
      break;
    case 'php7-cgi':
      $packages[] = 'php7.0-cgi';
      break;
  }
  $packages[] = 'php7.0-xml';
  $packages[] = 'php7.0-curl';
  $packages[] = 'php7.0-gd';
  $packages[] = 'php7.0-json';
  $packages[] = 'php7.0-mbstring';

  // DB.
  switch ($entity->field_webspace_database->value) {
    case 'mariadb':
      $packages[] = 'mariadb-server';
      $packages[] = 'php7.0-mysql';
      $packages_script[] = 'mysql -u root -e "
        CREATE USER \'drupal\'@\'localhost\' IDENTIFIED BY \'drupal\';
        GRANT USAGE ON *.* TO \'drupal\'@\'localhost\' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
        CREATE DATABASE IF NOT EXISTS \`drupal\`;
        GRANT ALL PRIVILEGES ON \`drupal\`.* TO \'drupal\'@\'localhost\'"';
      break;
    case 'mysql':
      $packages[] = 'mysql-server';
      $packages[] = 'php7.0-mysql';
      break;
    case 'sqllite':
      $packages[] = 'php7.0-sqlite3';
      break;
    case 'postgresql':
      $packages[] = 'postgresql';
      $packages[] = 'php7.0-pgsql';
      break;
  }

  // Webserver.
  switch ($entity->field_webspace_webserver->value) {
    case 'nginx':
      $packages[] = "nginx";
      switch ($entity->field_webspace_interpreter->value) {
        case 'php7-fpm':
          $packages_script[] = 'echo "
            server {
              listen 80;
              server_name *.ply.st;
              root /var/www/html;
              index index.php;
              location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
              }
            }" > /etc/nginx/sites-enabled/default';
          break;
        case 'mod-php7':
          throw new Error('Cannot use mod-php7 with nginx');
          break;
        case 'php7-cgi':
          // @todo
          $packages_script[] = 'echo "
            server {
              listen 80;
              server_name *.ply.st;
              root /var/www/html;
              index index.php;
              location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass 127.0.0.1:9000;
              }
            }" > /etc/nginx/sites-enabled/default';
          break;
      }
      $packages_script[] = 'service nginx reload';
      break;
    case 'apache2':
      $packages[] = "apache2";
      $packages_script[] = 'a2enmod rewrite';
      $packages_script[] = 'echo "
        <Directory /var/www/html>
          Options FollowSymLinks
          AllowOverride All
        </Directory>" >> /etc/apache2/sites-enabled/000-default.conf';
      $packages_script[] = 'service apache2 restart';

      switch ($entity->field_webspace_interpreter->value) {
        case 'php7-fpm':
          // @todo
          break;
        case 'mod-php7':
          $packages[] = 'libapache2-mod-php7.0';
          break;
        case 'php7-cgi':
          // @todo
          break;
      }
      $packages_script[] = 'rm /var/www/html/index.html';
      break;
  }

  $script[] = 'apt-get install -y ' . implode(' ', $packages);
  $script = array_merge($script, $packages_script);

  // Install composer.
  $script[] = 'php -r "copy(\'https://getcomposer.org/installer\', \'composer-setup.php\');"';
  $script[] = 'php composer-setup.php --quiet --install-dir=/usr/local/bin --filename=composer';
  $script[] = 'rm composer-setup.php';

  // Install drush.
  $script[] = 'php -r "readfile(\'https://s3.amazonaws.com/files.drush.org/drush.phar\');" > drush';
  $script[] = 'chmod +x drush';
  $script[] = 'mv drush /usr/local/bin';

  // Snapshot; Start fetching drupal projects.
  // @todo need snapshot cache invalidation to keep packages up to date
  $script[] = '#!/bin/bash';
  $script[] = 'export DEBIAN_FRONTEND=noninteractive';
  $script[] = 'set -x';
  // @todo actually install more than drupal core
  // @todo do this with non root user
  $script[] = 'composer create-project drupal-composer/drupal-project:8.x-dev /var/www/drupal --stability dev --no-interaction';
  $script[] = 'rm -rf /var/www/html';
  $script[] = 'ln -s /var/www/drupal/web /var/www/html';

  // Snapshot; Start installing drupal projects.
  // @todo if project is dev version we shouldn't snapshot cache (for too long).
  $script[] = '#!/bin/bash';
  $script[] = 'export DEBIAN_FRONTEND=noninteractive';
  $script[] = 'set -x';
  // Use webroot as cwd.
  $script[] = 'cd /var/www/drupal/web';
  // @todo if skipping drupal core installation, prefill database credentials and etc
  // @todo dynamic site name? one of the projects?
  // @todo do this with non root user
  $script[] = 'drush si -y --db-url=mysql://drupal:drupal@localhost/drupal --account-pass=admin --site-name=drupal';

  return implode("\n", $script);
}
