<?php

/**
 * @file
 * Provides managable sponsor blocks and advertisement.
 */

/**
 * Implements hook_menu().
 */
function simplytest_sponsors_menu() {
  $items = array();
  // Sponsor list configuration.
  $items['admin/simplytest/sponsors'] = array(
    'title' => 'Sponsors',
    'page callback' => 'drupal_get_form',
    'description' => 'Configure sponsoring blocks.',
    'page arguments' => array('simplytest_sponsors_configuration_form'),
    'access arguments' => array('administer simplytest'),
    'file' => 'simplytest_sponsors.admin.inc',
  );
  // Path for updating a sponsor entry.
  $items['admin/simplytest/sponsors/%/%'] = array(
    'title' => 'Sponsor',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simplytest_sponsors_operation', 3, 4),
    'access arguments' => array('administer simplytest'),
  );
  return $items;
}

/**
 * Confirms and executes an operation on a sponsor entry.
 */
function simplytest_sponsors_operation($form, $form_state, $id, $operation) {
  $form['#sponsor_id'] = $id;

  switch ($operation) {
    case 'delete':
      $form['#submit'][] = 'simplytest_sponsors_operation_delete';
      break;
    default:
      return $form;
      break;
  }

  $form = confirm_form(
    $form,
    t('Do you want to @operation this sponsor entry?', array('@operation' => $operation, '%id' => $id)),
    'admin/simplytest/sponsors'
  );
  return $form;
}

/**
 * Deletes an sponsor entry after confirmation.
 */
function simplytest_sponsors_operation_delete($form, $form_state) {
  // Delete sponsor entry.
  $sponsors = variable_get('simplytest_sponsors', array());
  unset($sponsors[$form['#sponsor_id']]);
  variable_set('simplytest_sponsors', $sponsors);
  drupal_goto('admin/simplytest/sponsors');
}

/**
 * Implements hook_theme().
 */
function simplytest_sponsors_theme() {
  return array(
    'simplytest_sponsors_configuration_form' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function simplytest_sponsors_block_info() {
  $blocks = array();
  $blocks['simplytest_sponsors_list'] = array(
    'info' => t('simplytest sponsors - sponsor list'),
    'status' => TRUE,
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => "<front>\nproject/*\nproject",
    'region' => 'featured',
    'weight' => 1000,
  );
  $blocks['simplytest_sponsors_ad'] = array(
    'info' => t('simplytest sponsors - advertisement'),
    'status' => TRUE,
    'cache' => DRUPAL_NO_CACHE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => "progress/*",
    'region' => 'footer_first',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function simplytest_sponsors_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'simplytest_sponsors_list':
      $block['subject'] = NULL;
      $block['content'] = simplytest_sponsors_block_list();
      break;
    case 'simplytest_sponsors_ad':
      $block['subject'] = NULL;
      $block['content'] = simplytest_sponsors_block_ad();
      break;
  }
  return $block;
}

/**
 * Prints out a list of sponsor embeds.
 */
function simplytest_sponsors_block_list() {
  $sponsors = variable_get('simplytest_sponsors', array());
  $items = array();
  foreach ($sponsors as $sponsor) {
    if ($sponsor['active']) {
      $items[] = $sponsor['list_embed'];
    }
  }
  return array(
    '#theme' => 'item_list',
    '#items' => $items,
  );
}

/**
 * Prints a slideable sponsoring advertisement.
 */
function simplytest_sponsors_block_ad() {
  // Get all sponsor ads and randomize order.
  $sponsors = variable_get('simplytest_sponsors', array());
  foreach ($sponsors as $number => $sponsor) {
    if (!$sponsor['active'] || empty($sponsor['ad_embed'])) {
      unset($sponsors[$number]);
    }
  }
  shuffle($sponsors);

  $output = '';
  // Generate slide content.
  if (count($sponsors) > 1) {
    $output .= '<div class="sponsor-ad-slide">';
    foreach ($sponsors as $number => $sponsor) {
        $output .= '<div class="sponsor-ad-embed slide-' . $number . '">' . $sponsor['ad_embed'] . '</div>';
    }
    $output .= '</div>';
  }

  // Single slide.
  else {
    foreach ($sponsors as $sponsor) {
       $output .= '<div class="sponsor-ad-embed slide-single">' . $sponsor['ad_embed'] . '</div>';
    }
  }

  if (!empty($output)) {
    $output .= '<span class="sponsor-ad-info">' . t('Sponsor advertisement') . '</span>';
  }
  return $output;
}