<?php

/**
 * @file
 * Provides an issue summary block pulled from drupal.org.
 */

/**
 * Implements hook_block_info().
 */
function simplytest_issues_block_info() {
  $blocks = array();
  $blocks['simplytest_issues'] = array(
    'info' => t('simplytest issues'),
    'status' => TRUE,
    'cache' => DRUPAL_CACHE_CUSTOM,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => "<front>\nproject/*\nproject",
    'region' => 'footer_first',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function simplytest_issues_block_view($delta = '') {
  $block = array();
  if ($delta == 'simplytest_issues') {
    $block['subject'] = t('Issues');
    // Check whether we've pulled the data recently.
    if ($cached = (@cache_get('simplytest_issues')->data)) {
      $block['content'] = $cached['text'];
    }
    else {
      $block['content'] = t('No issue data available.');
    }
  }
  return $block;
}

/**
 * Implements hook_cron().
 */
function simplytest_cron() {
  // Request fresh data.
  $result = drupal_http_request('http://www.drupal.org/project/simplytest');
  if ($result->code != 200 || !isset($result->data)) {
    watchdog('simplytest_issues', 'Failed to fetch issues from drupal.org. (HTTP Request failed)', array(), WATCHDOG_ERROR);
  }
  // Try to match out the issue summary block.
  preg_match_all('!<div class="issue-cockpit-categories">(.*)</div>[^<]*<div class="issue-cockpit-subscribe">!s', $result->data, $issues);
  if(!isset($issues[1][0])) {
    watchdog('simplytest_issues', 'Failed to fetch issues from drupal.org. (PREG MATCH failed)', array(), WATCHDOG_WARNING);
  }

  $text = t('Drupal.org issues') . $issues[1][0];
  $text = str_replace('/project/issues/', 'http://www.drupal.org/project/issues/', $text);
  $text .= '
    <div class="issue-nav">
      <a href="http://www.drupal.org/node/add/project-issue/simplytest">' . t('Open a new issue') . '</a>
      <a href="http://www.drupal.org/project/issues/search/simplytest">' . t('Search issues') . '</a>
    </div>';
  cache_set('simplytest_issues', array('time' => REQUEST_TIME, 'text' => $text));

  watchdog('simplytest_issues', 'Successfully pulled issue overview.');
}
